# Generated by Django 6.0 on 2025-12-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_venta_total_alter_venta_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha del análisis')),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de ventas del día')),
                ('promedio_ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Promedio de ganancia (20%)')),
                ('ahorro', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ahorro (30% del promedio)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Análisis de Venta',
                'verbose_name_plural': 'Análisis de Ventas',
                'db_table': 'analisis_ventas',
                'ordering': ['-fecha'],
            },
        ),
    ]
